# Financial Crisis
Financial crises are a frequent cause of recession and economic hardship.  Financial crises tend to unfold in a well know pattern.  The financial upswing base on (say) housing will follow an increase in house prices that feeds into increase borrowing, partly facilitated by the rise in asset prices (housing) that allows credit-constrained households to access more funds. At some point house prices fall. It is not always clear what triggers the reversal or bursting of the bubble.  Now the decline in the value of collateral will cause households to reduce their debt and borrowing so that there is a feedback effect on house prices. If the downswing in finance becomes severe this can turn into a banking crisis: households become Involvement and cannot re-pay their loans and as a result banks find their own solvency questioned. 

The standard macro model, working through the IS curve, is based on the belief that households and firm can carry out their spending plans by accessing finance from the financial system. Banks have a major role in the economy and get greater protection from the government than non-financial firms because of the need to ensure that the economy runs smoothly.  The collapse of Lehman Brothers in 2008 showed the contagion in the financial system is a real threat.  However, the government will want to ensure that there is a balance between providing support and preventing moral hazard. 

The positive probability that a collapsed bank would be bailed out by the government must affect the decision-making of the commercial banks.  Some of the cost of collapse have been socialised and there is a wedge between the private and social costs of collapse.  There would be a tendency to take greater risk. There is also a market failure: banks will work on the private cost benefit while there are some social costs to bank collapse in terms of the public good that is the smoothly operating financial system. The response to this externally is to control the amount of capital that a bank will hold.   

Banks make loans to households and firms, they can also engage in other financial activities.  Bank activity can be divided into retail and investment. Many banks are Universal banks and conduct each of these activities.  The investment bank conducts trading of financial securities and has a trading book that is marked-to-market.  It is assumed here that investment banks are risk-neutral and that they use a business model called Value at risk. 
 
[@ReinhartRogoff] produce a database of financial crises since 1800. They characterise four types of financial crisis: 
1. Inflation, 
2. Currency, 
3. Sovereign debt 
4  banking. 

The focus here is banking crisis and the collapse of banks and households after a financial expansion. [@ReinhartRogoff] find three characteristics of a banking crisis:  

1. There is a large decline in asset prices (house prices down an average 35% over 6 years and equity prices down 55% over three or four years); 2. A fall in GDP (real per-capita GDP falls 9% peak to trough on average) and a rise in unemployment (7 percentage points);
3. An increase in government debt (a rise of an average 86 percentage points). 

In business cycles there is a fluctuation in GDP and employment and some changes in prices.  Welfare is lost as people become unemployed and find it difficult to get jobs. Therefore the central bank should try to minimise the fluctuations. The financial cycle is characterised by: an increase in house prices and lending; a culmination with a housing crash and a banking crisis; the downswing involves households and banks repairing their balance sheet by de-leveraging, meaning that the supply and demand for loans falls; households try to save more to recover from negative equity; the increase in public debt causes a focus on repairing the public balance sheet. Asset price bubbles and financial accelerators play a key role in the financial cycle. 

## Asset price bubbles
Dynamic processes can work in different ways in different markets.  If we use a diagram to compare the price of assets at time t and at time t + 1, the 45 degree line with provide the stability. The price-dynamic equation (PDE) shows the way that prices react in different markets.  In a market for non-durable goods the PDR will be flatter than the stability line because a rise in price today will bring an expectation that there will be a fall back towards the equilibrium in the future; if the PDE is steeper than the stability line it means that a price increase today leads to prices being even higher tomorrow (maybe because expected prices increase and shift the demand curve).  In the first case supply will exceed demand at the higher prices, in the second case the demand curve shifts (and maybe even the supply curve as well). The bubble can continue until there is something to question the continued deviation from *fundamental value*. The third case has an S-shaped PDE that has multiple equilibria. The formula for PDE can be written as 

$$P_{t + 1} = f(P_t, A_t)$$

Were A_t is the variable that shifts the curve.  A could be the proportion of people who base expectations on what happened in the last period. Therefore a negative shock to house prices can start with the market reacting in a *normal* way but may eventually change the proportion of people with expectations being formed on fundamentals and cause a swift to a feed-back mechanism that causes much larger changes in price. This is where self-fulfilling expectations can operate for durable goods. ASIDE:  think also about the rational bubble and the expectations that are formed by looking at what other people think as well as exiting the theatre compared to entering the theatre. 

##Financial Accelerator
The financial accelerator is based on the fact that credit-constrained households can borrow against the collateral of their house once prices rise, Therefore there is a link between the rise in asset prices, the availability of credit and household spending,  Therefore, there is a link between asset prices and the IS curve. There is a feedback mechanism from asset prices to spending.  An increase in house prices increases the value of collateral, allows credit-constrained households to borrow more for spending and buying more houses. This pushes out the IS curve and causes a further rise in house prices. The IS curve is also affected (shifted) by the increase in house building. If here are no credit-constrained households, there are no feedback effects and no propagation.  There is only a minor wealth effect. 

## The paradox of stability. 
Hyman Minsky highlighted the way that stability could increase the risk in the economy. Economists do not usually like a model where there are *false beliefs*. Gordon Brown claimed that the new macroeconomic framework would put an end to boom and bust. 

##Balance sheet recessions
Balance sheet recessions (US 2007-10 and Japan in the 1990s) are different from usual recessions as they involve gradual adjustment to repaid balance sheets that have been damaged. Households and firms must deleverage and increase savings. There are some references in the text. There are two types of households: savers and borrowers. The savers are not credit-constrained, the act according to PIH and will save more when interest rates are high. Borrower households are credit constrained. They will borrow as much as they can and that is determined by the LTV ratio.  If the value of their house is below a target level, they will save to increase the asset value. Before the crash, the economy is equilibrium, savers and borrowers are at the target wealth, borrowers have borrowed to the maximum that is determined by the LTV ratio and the equity that they have on their house from the last period. The central bank has set interest rates at the level to hold inflation stable. A house price crash has a number of effects in this model. There are a number of features: LTV effect, collateral effect, banks calling in loans when people are *under water* and the increase in savings that takes places as household seek to repair balance sheets. IN this case there is scope for fiscal policy to act to stabilise aggregate demand. 


